NORTHWIND.WebMVC/Controllers/CustomersController.cs
using NORTHWIND.Common;
using NORTHWIND.Facade;
using NORTHWIND.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NORTHWIND.WebMVC.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        public ActionResult Index()
        { 
            return View();
        }


        [Route("List")]
        public ActionResult List()
        {
            var facade = new CustomersFacade();
            return Json(ApiResponse.OK(facade.GetAllItems()),JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Route("Paging")]
        public ActionResult Paging(PageData data)
        {
            var facade = new CustomersFacade();
            Dictionary<string, object> param = new Dictionary<string, object>();
            if (data.criteria != null)
                foreach (var crt in data.criteria)
                {
                    param[crt.criteria] = crt.value;
                }
            var rows = facade.GetListItemsByLikeCriteria(param, data.page, data.pageSize, data.order);
            var count = facade.GetListItemsByLikeCriteriaCount(param);
            var pageCount = Math.Ceiling(Commons.GetDouble(count) / data.pageSize);
            var apiResponse = ApiResponse.OK(new { rows = rows, rowCount = count, pageCount = pageCount });
            return Json(apiResponse);
        }

        // GET: Customers/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Customers/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Customers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NORTHWIND.WebMVC/Controllers/OrdersController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using NORTHWIND.Common;
using NORTHWIND.Facade;
using NORTHWIND.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace NORTHWIND.WebMVC.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Orders
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("Paging")]        
        public ActionResult Paging(PageData data)
        {
            var facade = new OrdersFacade();
            Dictionary<string, object> param = new Dictionary<string, object>();
            if (data.criteria != null)
                foreach (var crt in data.criteria)
                {
                    param[crt.criteria] = crt.value;
                }
            var page = facade.GetPageByCriteria(param, data.page, data.pageSize, data.order);
            var rows = page.Items;
            var count = page.TotalItems;
            var pageCount = page.TotalPages;
            var apiResponse = ApiResponse.OK(new { rows = rows, rowCount = count, pageCount = pageCount });
            return CustomJsonResult.Build(apiResponse);
        }
    }
}

NORTHWIND.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>NORTHWIND System</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/images/northwind.png" rel="Shortcut Icon" />
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/ionicons/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/dist/css/AdminLTE.css" rel="stylesheet" />
    <link href="~/Content/dist/css/skins/skin-red-light.css" rel="stylesheet" />
    <link href="~/Content/dist/css/skins/skin-green.css" rel="stylesheet" />
    <link href="~/Content/dist/css/skins/skin-blue.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/iCheck/flat/blue.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
    <link href="~/Content/gridview/griview.css" rel="stylesheet" />

    <script src="~/Scripts/plugins/jQuery/jQuery-2.1.4.min.js" charset="utf-8"></script>
    <script src="~/Scripts/plugins/jQueryUI/jquery-ui.min.js"></script>
    <script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/dist/js/app.js" charset="ISO-8859-1"></script>
    <script src="~/Scripts/gridview/gridview.js"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a id="LinkLogo" class="logo" >
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>N</b>WT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>NORTHWIND</b> <span style="font-size: 14px;">Traders</span></span>
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="notifications-menu">
                            <a href="#">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">10</span>
                            </a>
                        </li>
                        <li class="tasks-menu">
                            <a href="#">
                                <i class="fa fa-flag-o"></i>
                                <span class="label label-danger">9</span>
                            </a>
                        </li>
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Content/dist/img/user2-160x160.jpg" class="user-image" alt="User Image" />

                                <span ID="LabelUserName" Class="hidden-xs" >Herru Purnomo</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-header">
                                    <img src="~/Content/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
                                    <p>
                                        <span ID="LabelUserNameRole" >Administrator</span>
                                    </p>
                                    <p>
                                        <small>
                                            Main Job Function -
                                            <span ID="LabelMainJobFunction" ></span>
                                        </small>
                                    </p>
                                    <p>
                                        <small>
                                            Main Group -
                                            <span ID="LabelMainGroup" ></span>
                                        </small>
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-primary btn-flat"><i class="fa fa-user">&nbsp;</i>Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a ID="LinkButton1" Class="btn btn-danger btn-flat logout" >
                                            <i class="fa fa-sign-out">&nbsp;</i>Sign Out
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="">
                            <a id="buttonSignOut" CssClass="">
                                <i class="fa fa-sign-out"></i> Sign Out
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel" style="display: none">
                    <div class="pull-left image">
                        <img src="~/Content/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
                    </div>
                    <div class="pull-left info">
                        <p>Herru Purnomo</p>
                        <a href="#"><i class="fa fa-circle text-success"></i>Online</a>
                    </div>
                </div>
                <!-- search form -->
                <div class="sidebar-form" style="display: none">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search..." />
                        <span class="input-group-btn">
                            <!--<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>-->
                        </span>
                    </div>
                </div>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li id="menu-dashboard" class="treeview">
                        <a href="@Url.Action("Index","Home")">
                            <i class="fa fa-dashboard"></i><span>Dashboard</span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-user-secret"></i><span>Admin</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-user"></i>Users</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-gear"></i><span>Master</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li id="menu-customers"><a href="@Url.Action("Index","Customers")"><i class="fa fa-briefcase"></i>Customers</a></li>
                            <li id="menu-suppliers"><a href="#"><i class="fa fa-truck"></i>Suppliers</a></li>
                            <li id="menu-employees"><a href="#"><i class="fa fa-users"></i>Employees</a></li>
                            <li id="menu-shippers"><a href="#"><i class="fa fa-plane"></i>Shippers</a></li>
                            <li id="menu-products"><a href="#"><i class="fa fa-object-ungroup"></i>Products</a></li>
                            <li id="menu-categories"><a href="#"><i class="fa fa-object-group"></i>Categories</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-line-chart"></i><span>Transaction</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","Orders")"><i class="fa fa-exchange"></i>Orders</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-newspaper-o"></i><span>Report</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-file-pdf-o"></i>Report 1</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.ModuleName
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
                    <li class="active">Dashboard</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    @RenderBody()
                </div>
            </section>
        </div>
    </div> 
    <script type="text/javascript">
        function setActiveMenu(id) {
            $('.sidebar-menu li').removeClass('active');
            $('#' + id).parent().parent().addClass('active');
            $('#' + id).addClass('active');
        }

        function showBoxArea(a, b) {
            $('#' + a).fadeOut('fast', function () {
                $('#' + b).fadeIn('slow');
            });
        }

        $(function () {
            //handle multiple bootstrap modal
            $(document).on('show.bs.modal', '.modal', function () {
                var zIndex = 1040 + (10 * $('.modal:visible').length);
                $(this).css('z-index', zIndex);
                setTimeout(function () {
                    $('.modal-backdrop').not('.modal-stack').css('z-index', zIndex - 1).addClass('modal-stack');
                }, 0);
            });

            //handle multiple bootstrap modal
            $(document).on('hidden.bs.modal', '.modal', function () {
                $('.modal:visible').length && $(document.body).addClass('modal-open');
                $(document.body).removeAttr("style");
            });
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>