NORTHWIND.WebMVC/Controllers/CustomerNewController.cs
using NORTHWIND.Common;
using NORTHWIND.Entity;
using NORTHWIND.Facade;
using NORTHWIND.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NORTHWIND.WebMVC.Controllers
{
    public class CustomerNewController : Controller
    {
        // GET: CustomerNew
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Paging(PageData data)
        {
            var facade = new CustomersFacade();
            Dictionary<string, object> param = new Dictionary<string, object>();
            if (data.criteria != null)
                foreach (var crt in data.criteria)
                {
                    param[crt.criteria] = crt.value;
                }
            var rows = facade.GetListItemsByLikeCriteria(param, data.page, data.pageSize, data.order);
            var count = facade.GetListItemsByLikeCriteriaCount(param);
            var pageCount = Math.Ceiling(Commons.GetDouble(count) / data.pageSize);
            var apiResponse = ApiResponse.OK(new { rows = rows, rowCount = count, pageCount = pageCount });
            return Json(apiResponse);
        }

        [HttpPost]
        public ActionResult Create()
        {
            return this.PartialView();
        }
        [HttpPost]
        public ActionResult CreateSave(CustomerView model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PartialView("Create",model);
            }

            // todo db
            var facade = new CustomersFacade();
            var customer = new Customers();
            customer.CustomerID = model.CustomerID;
            customer.CompanyName = model.CompanyName;
            customer.ContactName = model.ContactName;
            customer.ContactTitle = model.ContactTitle;
            customer.Address = model.Address;
            customer.City = model.City;
            customer.Region = model.Region;
            customer.PostalCode = model.PostalCode;
            customer.Country = model.Country;
            customer.Phone = model.Phone;
            customer.Fax = model.Fax;

            try {
                facade.Insert(customer);
                return (ActionResult)this.Content(@"ok");
            }
            catch (Exception ex) {
                this.ModelState.AddModelError(String.Empty, ex.Message);
            }
            return this.PartialView("Create", model);
        }
    }
}

NORTHWIND.WebMVC/Views/CustomerNew/Create.cshtml
@model NORTHWIND.WebMVC.Models.CustomerView
@using(
    Ajax.BeginForm("CreateSave","CustomerNew", new AjaxOptions { HttpMethod = "POST", OnSuccess = "Apx.AjaxOnSuccess"}))
{
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <span class="close" data-dismiss="modal">&times;</span>
            <h4 class="modal-title">Create Customer</h4>
        </div>
        <div class="modal-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, String.Empty, new  { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(e => e.CustomerID, new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                                @Html.EditorFor(e => e.CustomerID, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(e => e.CustomerID, String.Empty, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.CompanyName, new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                            @Html.EditorFor(e => e.CompanyName, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.CompanyName, String.Empty, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.ContactName, new { @class = "control-label col-md-3" })
                            <div class="col-md-6">
                            @Html.EditorFor(e => e.ContactName, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.ContactName, String.Empty, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.ContactTitle, new { @class = "control-label" })
                            @Html.EditorFor(e => e.ContactTitle, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.ContactTitle, String.Empty, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.Address, new { @class = "control-label" })
                            @Html.EditorFor(e => e.Address, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.Address, String.Empty, new { @class = "text-danger" })
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(e => e.City, new { @class = "control-label" })
                            @Html.EditorFor(e => e.City, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.City, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(e => e.Region, new { @class = "control-label" })
                            @Html.EditorFor(e => e.Region, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.Region, String.Empty, new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(e => e.PostalCode, new { @class = "control-label" })
                            @Html.EditorFor(e => e.PostalCode, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.PostalCode, String.Empty, new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(e => e.Country, new { @class = "control-label" })
                            @Html.EditorFor(e => e.Country, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.Country, String.Empty, new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(e => e.Phone, new { @class = "control-label" })
                            @Html.EditorFor(e => e.Phone, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.Phone, String.Empty, new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(e => e.Fax, new { @class = "control-label" })
                            @Html.EditorFor(e => e.Fax, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(e => e.Fax, String.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-danger" type="button" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>
}

NORTHWIND.WebMVC/Views/CustomerNew/Index.cshtml
@{
    ViewBag.Title = "Index";
    ViewBag.ModuleName = "Customers";
}

@section scripts
{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
    var Apx;
    $(function () {
        Apx = {
            grid: null,
            init: function () {
                this.initGrid();
                $('#actionCreate').on('click', Apx.loadActionCreate);
            },
            initGrid: function () {
                var elm = $('#gridview');
                this.grid = elm.gridView({
                    url: "@Url.Action("Paging", "CustomerNew")",
                    columns: [
                        {
                            header: '', data: 'CustomerID', render: function (data) {
                                return '<a href="#" onclick="showPopUp(\'' + data + '\')"><span class="fa fa-search"></span></a>\
                                        <a href="#" onClick="showPopUp()" style="color: green; margin-left: 6px;"><span class="fa fa-edit"></span></a>\
                                        <a href= "#" onClick="Delete(\'' + data + '\')" style= "color: red; margin-left: 6px;" ><span class="fa fa-trash"></span></a > ';
                            }
                        },
                        { header: 'Customer ID', data: 'CustomerID', sortable: true },
                        { header: 'Company Name', data: 'CompanyName', sortable: true },
                        { header: 'Contact Title', data: 'ContactTitle', sortable: true },
                        { header: 'Contact Name', data: 'ContactName', sortable: true },
                        { header: 'Address', data: 'Address', sortable: true },
                        { header: 'City', data: 'City', sortable: true }
                    ],
                    defaultSortExpression: 'CustomerID'
                })
            },
            gridAction: function (data) {

            },
            loadActionCreate : function (event) {
                event.preventDefault();
                var url = $(this).attr('href');
                $.post(url, function (data) {
                    $('#data-detail').html(data);
                    $('#modal-container').modal();
                })
            },
            AjaxOnSuccess: function (data) {
                if (data !== 'ok') {
                    $('#data-detail').html(data);
                    return;
                }
                $('#modal-container').modal('hide');
                $('#data-detail').html("");
                Apx.grid.reload();
            }
        };
        Apx.init();
    });

    function showModal(data) {
        alert('You click '+data);
    }

    function refresh() {
        gridview.reload();
    }
    </script>
}

<div class="col-md-12">
    <div class="box box-success">
        <div class="box-header with-border">
            <button class="btn btn-default vtn-sm" onclick="switchSearch();"><i class="fa fa-search"></i></button>

            <div class="btn-group pull-right btn-sm">
                <button type="button" class="btn btn-default" onclick="refresh()"><span class="fa fa-refresh"></span> Refresh</button>
                <button type="button" id="actionCreate" class="btn btn-primary" href="@Url.Action("Create","CustomerNew")">
                    <i class="glyphicon glyphicon-plus-sign"></i> Add New
                </button>
            </div>

        </div>
        <div class="box-body">
            <div id="gridview" style="">
            </div>
        </div>
        <div class="box-footer">

        </div>
    </div>
</div>

<div id="modal-container" class="modal fade" data-backdrop="static">
    <div id="data-detail"></div>
</div>